---
# tasks file for roles/run_infra
# pull docker image dynamically

# Pull Docker Image
- name: Pull Docker Image
  docker_image:
    name: "{{ image_name }}"
    source: pull
  become: yes

# Run Docker Container
- name: Run Docker Container
  docker_container:
    name: "flask"
    image: "{{ image_name }}"
    state: started
    ports:
      - "5000:5000"
  become: yes
